In [1]:
l=[1,2,3,4]
import numpy as np

In [2]:
np.array(l)

array([1, 2, 3, 4])

In [3]:
l=[1,2,3,'a',2.34,1+2j]

In [4]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [5]:
np.array([1,2,1.3,4,5])

array([ 1. ,  2. ,  1.3,  4. ,  5. ])

In [6]:
range(1,10)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
range(1,5,1)

[1, 2, 3, 4]

In [8]:
range(0,1,0.1)

TypeError: range() integer step argument expected, got float.

In [9]:
xrange(0,1,0.1)

TypeError: integer argument expected, got float

In [10]:
np.arange(1,2,0.1)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9])

In [1]:
import numpy as np
l1=range(10)
l2=range(10,20)
ar1=np.array(l1)
ar2=np.array(l2)

In [2]:
print [i+j for i,j in zip(l1,l2)]
print [i*j for i,j in zip(l1,l2)]

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]
[0, 11, 24, 39, 56, 75, 96, 119, 144, 171]


In [3]:
print ar1+ar2
print ar1*ar2


[10 12 14 16 18 20 22 24 26 28]
[  0  11  24  39  56  75  96 119 144 171]


In [7]:
%%capture timeit_result
%timeit [i+j for i,j in zip(l1,l2)]
%timeit [i*j for i,j in zip(l1,l2)]
%timeit ar1+ar2
%timeit ar1*ar2

In [8]:
print timeit_result

The slowest run took 12.60 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.08 us per loop
The slowest run took 4.01 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.15 us per loop
The slowest run took 281.75 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 799 ns per loop
The slowest run took 19.31 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 827 ns per loop



In [9]:
l=[
    [1,2,3],
    [4,5,6,7]
]

In [10]:
l[0]

[1, 2, 3]

In [11]:
for i in l:
    print i[0]

1
4


In [12]:
range(1,10)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
ar1=np.arange(20)

In [14]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
ar2=ar1.reshape(3,3)

ValueError: total size of new array must be unchanged

In [16]:
ar2=ar1.reshape(5,4)

In [17]:
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [19]:
ar2[:,:1]

array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]])

In [20]:
l=range(20)
ar1=np.array(l)

In [21]:
l2=l[1:5]

In [22]:
l2

[1, 2, 3, 4]

In [23]:
ar2=ar1[1:5]

In [24]:
ar2

array([1, 2, 3, 4])

In [29]:
l2[0]=100
l2

[100, 2, 3, 4]

In [30]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [32]:
ar2[0]=1000
ar2

array([1000,    2,    3,    4])

In [33]:
ar1

array([   0, 1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [34]:
ar2

array([1000,    2,    3,    4])

In [35]:
ar1

array([   0, 1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [36]:
ar3=ar1.reshape(5,4)

In [37]:
ar3

array([[   0, 1000,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15],
       [  16,   17,   18,   19]])

In [38]:
ar3.ndim

2

In [39]:
ar3.size

20

In [40]:
ar3.shape

(5, 4)

In [41]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [42]:
ar1

array([   0, 1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [43]:
l[12]=2356.3569

In [44]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 2356.3569, 13, 14, 15, 16, 17, 18, 19]

In [45]:
ar1[12]=2356.3569

In [46]:
ar1

array([   0, 1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11, 2356,   13,   14,   15,   16,   17,   18,   19])

In [47]:
ar1.dtype

dtype('int64')

In [48]:
l=[1,2,3,'23',34+2j,3.45]

In [49]:
np.array(l)

array(['1', '2', '3', '23', '(34+2j)', '3.45'], 
      dtype='|S21')

In [50]:
np.array(l,dtype='int')

TypeError: can't convert complex to long

In [51]:
np.array(l,dtype='complex')

TypeError: a float is required

In [52]:
l=[1,2,3,4,5.6]

In [53]:
np.array(l)

array([ 1. ,  2. ,  3. ,  4. ,  5.6])

In [54]:
np.array(l,dtype="int")

array([1, 2, 3, 4, 5])

In [55]:
int(1+2j)

TypeError: can't convert complex to int